export const colors =  {
    red: {
        filled: { background: 'bg-red-500', foreground: 'text-white', hover: 'hover:bg-red-400', active: 'active:bg-red-600', focus: 'focus:ring-2 focus:ring-red-400 ring-offset-1', border: 'border border-red-500' },
        outline: { background: 'bg-transparent', foreground: 'text-red-500', hover: 'hover:bg-red-100', active: 'active:bg-red-200', focus: 'focus:ring-2 focus:ring-red-400 ring-offset-1', border: 'border border-red-500' },
        light: { background: 'bg-red-200', foreground: 'text-red-800', hover: 'hover:bg-red-100', active: 'active:bg-red-300', focus: 'focus:ring-2 focus:ring-red-400 ring-offset-1', border: 'border border-red-300' },
        dark: { background: 'bg-red-800', foreground: 'text-white', hover: 'hover:bg-red-700', active: 'active:bg-red-900', focus: 'focus:ring-2 focus:ring-red-500 ring-offset-1', border: 'border border-red-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-red-500', hover: 'hover:bg-red-100', active: 'active:bg-red-200', focus: 'focus:ring-2 focus:ring-red-400 ring-offset-1', border: 'border border-transparent' },
    },
    orange: {
        filled: { background: 'bg-orange-500', foreground: 'text-white', hover: 'hover:bg-orange-400', active: 'active:bg-orange-600', focus: 'focus:ring-2 focus:ring-orange-400 ring-offset-1', border: 'border border-orange-500' },
        outline: { background: 'bg-transparent', foreground: 'text-orange-500', hover: 'hover:bg-orange-100', active: 'active:bg-orange-200', focus: 'focus:ring-2 focus:ring-orange-400 ring-offset-1', border: 'border border-orange-500' },
        light: { background: 'bg-orange-200', foreground: 'text-orange-800', hover: 'hover:bg-orange-100', active: 'active:bg-orange-300', focus: 'focus:ring-2 focus:ring-orange-400 ring-offset-1', border: 'border border-orange-300' },
        dark: { background: 'bg-orange-800', foreground: 'text-white', hover: 'hover:bg-orange-700', active: 'active:bg-orange-900', focus: 'focus:ring-2 focus:ring-orange-500 ring-offset-1', border: 'border border-orange-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-orange-500', hover: 'hover:bg-orange-100', active: 'active:bg-orange-200', focus: 'focus:ring-2 focus:ring-orange-400 ring-offset-1', border: 'border border-transparent' },
    },
    amber: {
        filled: { background: 'bg-amber-500', foreground: 'text-white', hover: 'hover:bg-amber-400', active: 'active:bg-amber-600', focus: 'focus:ring-2 focus:ring-amber-400 ring-offset-1', border: 'border border-amber-500' },
        outline: { background: 'bg-transparent', foreground: 'text-amber-500', hover: 'hover:bg-amber-100', active: 'active:bg-amber-200', focus: 'focus:ring-2 focus:ring-amber-400 ring-offset-1', border: 'border border-amber-500' },
        light: { background: 'bg-amber-200', foreground: 'text-amber-800', hover: 'hover:bg-amber-100', active: 'active:bg-amber-300', focus: 'focus:ring-2 focus:ring-amber-400 ring-offset-1', border: 'border border-amber-300' },
        dark: { background: 'bg-amber-800', foreground: 'text-white', hover: 'hover:bg-amber-700', active: 'active:bg-amber-900', focus: 'focus:ring-2 focus:ring-amber-500 ring-offset-1', border: 'border border-amber-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-amber-500', hover: 'hover:bg-amber-100', active: 'active:bg-amber-200', focus: 'focus:ring-2 focus:ring-amber-400 ring-offset-1', border: 'border border-transparent' },
    },
    yellow: {
        filled: { background: 'bg-yellow-500', foreground: 'text-white', hover: 'hover:bg-yellow-400', active: 'active:bg-yellow-600', focus: 'focus:ring-2 focus:ring-yellow-400 ring-offset-1', border: 'border border-yellow-500' },
        outline: { background: 'bg-transparent', foreground: 'text-yellow-500', hover: 'hover:bg-yellow-100', active: 'active:bg-yellow-200', focus: 'focus:ring-2 focus:ring-yellow-400 ring-offset-1', border: 'border border-yellow-500' },
        light: { background: 'bg-yellow-200', foreground: 'text-yellow-800', hover: 'hover:bg-yellow-100', active: 'active:bg-yellow-300', focus: 'focus:ring-2 focus:ring-yellow-400 ring-offset-1', border: 'border border-yellow-300' },
        dark: { background: 'bg-yellow-800', foreground: 'text-white', hover: 'hover:bg-yellow-700', active: 'active:bg-yellow-900', focus: 'focus:ring-2 focus:ring-yellow-500 ring-offset-1', border: 'border border-yellow-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-yellow-500', hover: 'hover:bg-yellow-100', active: 'active:bg-yellow-200', focus: 'focus:ring-2 focus:ring-yellow-400 ring-offset-1', border: 'border border-transparent' },
    },
    lime: {
        filled: { background: 'bg-lime-500', foreground: 'text-white', hover: 'hover:bg-lime-400', active: 'active:bg-lime-600', focus: 'focus:ring-2 focus:ring-lime-400 ring-offset-1', border: 'border border-lime-500' },
        outline: { background: 'bg-transparent', foreground: 'text-lime-500', hover: 'hover:bg-lime-100', active: 'active:bg-lime-200', focus: 'focus:ring-2 focus:ring-lime-400 ring-offset-1', border: 'border border-lime-500' },
        light: { background: 'bg-lime-200', foreground: 'text-lime-800', hover: 'hover:bg-lime-100', active: 'active:bg-lime-300', focus: 'focus:ring-2 focus:ring-lime-400 ring-offset-1', border: 'border border-lime-300' },
        dark: { background: 'bg-lime-800', foreground: 'text-white', hover: 'hover:bg-lime-700', active: 'active:bg-lime-900', focus: 'focus:ring-2 focus:ring-lime-500 ring-offset-1', border: 'border border-lime-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-lime-500', hover: 'hover:bg-lime-100', active: 'active:bg-lime-200', focus: 'focus:ring-2 focus:ring-lime-400 ring-offset-1', border: 'border border-transparent' },
    },
    green: {
        filled: { background: 'bg-green-500', foreground: 'text-white', hover: 'hover:bg-green-400', active: 'active:bg-green-600', focus: 'focus:ring-2 focus:ring-green-400 ring-offset-1', border: 'border border-green-500' },
        outline: { background: 'bg-transparent', foreground: 'text-green-500', hover: 'hover:bg-green-100', active: 'active:bg-green-200', focus: 'focus:ring-2 focus:ring-green-400 ring-offset-1', border: 'border border-green-500' },
        light: { background: 'bg-green-200', foreground: 'text-green-800', hover: 'hover:bg-green-100', active: 'active:bg-green-300', focus: 'focus:ring-2 focus:ring-green-400 ring-offset-1', border: 'border border-green-300' },
        dark: { background: 'bg-green-800', foreground: 'text-white', hover: 'hover:bg-green-700', active: 'active:bg-green-900', focus: 'focus:ring-2 focus:ring-green-500 ring-offset-1', border: 'border border-green-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-green-500', hover: 'hover:bg-green-100', active: 'active:bg-green-200', focus: 'focus:ring-2 focus:ring-green-400 ring-offset-1', border: 'border border-transparent' },
    },
    emerald: {
        filled: { background: 'bg-emerald-500', foreground: 'text-white', hover: 'hover:bg-emerald-400', active: 'active:bg-emerald-600', focus: 'focus:ring-2 focus:ring-emerald-400 ring-offset-1', border: 'border border-emerald-500' },
        outline: { background: 'bg-transparent', foreground: 'text-emerald-500', hover: 'hover:bg-emerald-100', active: 'active:bg-emerald-200', focus: 'focus:ring-2 focus:ring-emerald-400 ring-offset-1', border: 'border border-emerald-500' },
        light: { background: 'bg-emerald-200', foreground: 'text-emerald-800', hover: 'hover:bg-emerald-100', active: 'active:bg-emerald-300', focus: 'focus:ring-2 focus:ring-emerald-400 ring-offset-1', border: 'border border-emerald-300' },
        dark: { background: 'bg-emerald-800', foreground: 'text-white', hover: 'hover:bg-emerald-700', active: 'active:bg-emerald-900', focus: 'focus:ring-2 focus:ring-emerald-500 ring-offset-1', border: 'border border-emerald-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-emerald-500', hover: 'hover:bg-emerald-100', active: 'active:bg-emerald-200', focus: 'focus:ring-2 focus:ring-emerald-400 ring-offset-1', border: 'border border-transparent' },
    },
    teal: {
        filled: { background: 'bg-teal-500', foreground: 'text-white', hover: 'hover:bg-teal-400', active: 'active:bg-teal-600', focus: 'focus:ring-2 focus:ring-teal-400 ring-offset-1', border: 'border border-teal-500' },
        outline: { background: 'bg-transparent', foreground: 'text-teal-500', hover: 'hover:bg-teal-100', active: 'active:bg-teal-200', focus: 'focus:ring-2 focus:ring-teal-400 ring-offset-1', border: 'border border-teal-500' },
        light: { background: 'bg-teal-200', foreground: 'text-teal-800', hover: 'hover:bg-teal-100', active: 'active:bg-teal-300', focus: 'focus:ring-2 focus:ring-teal-400 ring-offset-1', border: 'border border-teal-300' },
        dark: { background: 'bg-teal-800', foreground: 'text-white', hover: 'hover:bg-teal-700', active: 'active:bg-teal-900', focus: 'focus:ring-2 focus:ring-teal-500 ring-offset-1', border: 'border border-teal-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-teal-500', hover: 'hover:bg-teal-100', active: 'active:bg-teal-200', focus: 'focus:ring-2 focus:ring-teal-400 ring-offset-1', border: 'border border-transparent' },
    },
    cyan: {
        filled: { background: 'bg-cyan-500', foreground: 'text-white', hover: 'hover:bg-cyan-400', active: 'active:bg-cyan-600', focus: 'focus:ring-2 focus:ring-cyan-400 ring-offset-1', border: 'border border-cyan-500' },
        outline: { background: 'bg-transparent', foreground: 'text-cyan-500', hover: 'hover:bg-cyan-100', active: 'active:bg-cyan-200', focus: 'focus:ring-2 focus:ring-cyan-400 ring-offset-1', border: 'border border-cyan-500' },
        light: { background: 'bg-cyan-200', foreground: 'text-cyan-800', hover: 'hover:bg-cyan-100', active: 'active:bg-cyan-300', focus: 'focus:ring-2 focus:ring-cyan-400 ring-offset-1', border: 'border border-cyan-300' },
        dark: { background: 'bg-cyan-800', foreground: 'text-white', hover: 'hover:bg-cyan-700', active: 'active:bg-cyan-900', focus: 'focus:ring-2 focus:ring-cyan-500 ring-offset-1', border: 'border border-cyan-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-cyan-500', hover: 'hover:bg-cyan-100', active: 'active:bg-cyan-200', focus: 'focus:ring-2 focus:ring-cyan-400 ring-offset-1', border: 'border border-transparent' },
    },
    sky: {
        filled: { background: 'bg-sky-500', foreground: 'text-white', hover: 'hover:bg-sky-400', active: 'active:bg-sky-600', focus: 'focus:ring-2 focus:ring-sky-400 ring-offset-1', border: 'border border-sky-500' },
        outline: { background: 'bg-transparent', foreground: 'text-sky-500', hover: 'hover:bg-sky-100', active: 'active:bg-sky-200', focus: 'focus:ring-2 focus:ring-sky-400 ring-offset-1', border: 'border border-sky-500' },
        light: { background: 'bg-sky-200', foreground: 'text-sky-800', hover: 'hover:bg-sky-100', active: 'active:bg-sky-300', focus: 'focus:ring-2 focus:ring-sky-400 ring-offset-1', border: 'border border-sky-300' },
        dark: { background: 'bg-sky-800', foreground: 'text-white', hover: 'hover:bg-sky-700', active: 'active:bg-sky-900', focus: 'focus:ring-2 focus:ring-sky-500 ring-offset-1', border: 'border border-sky-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-sky-500', hover: 'hover:bg-sky-100', active: 'active:bg-sky-200', focus: 'focus:ring-2 focus:ring-sky-400 ring-offset-1', border: 'border border-transparent' },
    },
    blue: {
        filled: { background: 'bg-blue-500', foreground: 'text-white', hover: 'hover:bg-blue-400', active: 'active:bg-blue-600', focus: 'focus:ring-2 focus:ring-blue-400 ring-offset-1', border: 'border border-blue-500' },
        outline: { background: 'bg-transparent', foreground: 'text-blue-500', hover: 'hover:bg-blue-100', active: 'active:bg-blue-200', focus: 'focus:ring-2 focus:ring-blue-400 ring-offset-1', border: 'border border-blue-500' },
        light: { background: 'bg-blue-200', foreground: 'text-blue-800', hover: 'hover:bg-blue-100', active: 'active:bg-blue-300', focus: 'focus:ring-2 focus:ring-blue-400 ring-offset-1', border: 'border border-blue-300' },
        dark: { background: 'bg-blue-800', foreground: 'text-white', hover: 'hover:bg-blue-700', active: 'active:bg-blue-900', focus: 'focus:ring-2 focus:ring-blue-500 ring-offset-1', border: 'border border-blue-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-blue-500', hover: 'hover:bg-blue-100', active: 'active:bg-blue-200', focus: 'focus:ring-2 focus:ring-blue-400 ring-offset-1', border: 'border border-transparent' },
    },
    indigo: {
        filled: { background: 'bg-indigo-500', foreground: 'text-white', hover: 'hover:bg-indigo-400', active: 'active:bg-indigo-600', focus: 'focus:ring-2 focus:ring-indigo-400 ring-offset-1', border: 'border border-indigo-500' },
        outline: { background: 'bg-transparent', foreground: 'text-indigo-500', hover: 'hover:bg-indigo-100', active: 'active:bg-indigo-200', focus: 'focus:ring-2 focus:ring-indigo-400 ring-offset-1', border: 'border border-indigo-500' },
        light: { background: 'bg-indigo-200', foreground: 'text-indigo-800', hover: 'hover:bg-indigo-100', active: 'active:bg-indigo-300', focus: 'focus:ring-2 focus:ring-indigo-400 ring-offset-1', border: 'border border-indigo-300' },
        dark: { background: 'bg-indigo-800', foreground: 'text-white', hover: 'hover:bg-indigo-700', active: 'active:bg-indigo-900', focus: 'focus:ring-2 focus:ring-indigo-500 ring-offset-1', border: 'border border-indigo-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-indigo-500', hover: 'hover:bg-indigo-100', active: 'active:bg-indigo-200', focus: 'focus:ring-2 focus:ring-indigo-400 ring-offset-1', border: 'border border-transparent' },
    },
    violet: {
        filled: { background: 'bg-violet-500', foreground: 'text-white', hover: 'hover:bg-violet-400', active: 'active:bg-violet-600', focus: 'focus:ring-2 focus:ring-violet-400 ring-offset-1', border: 'border border-violet-500' },
        outline: { background: 'bg-transparent', foreground: 'text-violet-500', hover: 'hover:bg-violet-100', active: 'active:bg-violet-200', focus: 'focus:ring-2 focus:ring-violet-400 ring-offset-1', border: 'border border-violet-500' },
        light: { background: 'bg-violet-200', foreground: 'text-violet-800', hover: 'hover:bg-violet-100', active: 'active:bg-violet-300', focus: 'focus:ring-2 focus:ring-violet-400 ring-offset-1', border: 'border border-violet-300' },
        dark: { background: 'bg-violet-800', foreground: 'text-white', hover: 'hover:bg-violet-700', active: 'active:bg-violet-900', focus: 'focus:ring-2 focus:ring-violet-500 ring-offset-1', border: 'border border-violet-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-violet-500', hover: 'hover:bg-violet-100', active: 'active:bg-violet-200', focus: 'focus:ring-2 focus:ring-violet-400 ring-offset-1', border: 'border border-transparent' },
    },
    purple: {
        filled: { background: 'bg-purple-500', foreground: 'text-white', hover: 'hover:bg-purple-400', active: 'active:bg-purple-600', focus: 'focus:ring-2 focus:ring-purple-400 ring-offset-1', border: 'border border-purple-500' },
        outline: { background: 'bg-transparent', foreground: 'text-purple-500', hover: 'hover:bg-purple-100', active: 'active:bg-purple-200', focus: 'focus:ring-2 focus:ring-purple-400 ring-offset-1', border: 'border border-purple-500' },
        light: { background: 'bg-purple-200', foreground: 'text-purple-800', hover: 'hover:bg-purple-100', active: 'active:bg-purple-300', focus: 'focus:ring-2 focus:ring-purple-400 ring-offset-1', border: 'border border-purple-300' },
        dark: { background: 'bg-purple-800', foreground: 'text-white', hover: 'hover:bg-purple-700', active: 'active:bg-purple-900', focus: 'focus:ring-2 focus:ring-purple-500 ring-offset-1', border: 'border border-purple-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-purple-500', hover: 'hover:bg-purple-100', active: 'active:bg-purple-200', focus: 'focus:ring-2 focus:ring-purple-400 ring-offset-1', border: 'border border-transparent' },
    },
    fuchsia: {
        filled: { background: 'bg-fuchsia-500', foreground: 'text-white', hover: 'hover:bg-fuchsia-400', active: 'active:bg-fuchsia-600', focus: 'focus:ring-2 focus:ring-fuchsia-400 ring-offset-1', border: 'border border-fuchsia-500' },
        outline: { background: 'bg-transparent', foreground: 'text-fuchsia-500', hover: 'hover:bg-fuchsia-100', active: 'active:bg-fuchsia-200', focus: 'focus:ring-2 focus:ring-fuchsia-400 ring-offset-1', border: 'border border-fuchsia-500' },
        light: { background: 'bg-fuchsia-200', foreground: 'text-fuchsia-800', hover: 'hover:bg-fuchsia-100', active: 'active:bg-fuchsia-300', focus: 'focus:ring-2 focus:ring-fuchsia-400 ring-offset-1', border: 'border border-fuchsia-300' },
        dark: { background: 'bg-fuchsia-800', foreground: 'text-white', hover: 'hover:bg-fuchsia-700', active: 'active:bg-fuchsia-900', focus: 'focus:ring-2 focus:ring-fuchsia-500 ring-offset-1', border: 'border border-fuchsia-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-fuchsia-500', hover: 'hover:bg-fuchsia-100', active: 'active:bg-fuchsia-200', focus: 'focus:ring-2 focus:ring-fuchsia-400 ring-offset-1', border: 'border border-transparent' },
    },
    pink: {
        filled: { background: 'bg-pink-500', foreground: 'text-white', hover: 'hover:bg-pink-400', active: 'active:bg-pink-600', focus: 'focus:ring-2 focus:ring-pink-400 ring-offset-1', border: 'border border-pink-500' },
        outline: { background: 'bg-transparent', foreground: 'text-pink-500', hover: 'hover:bg-pink-100', active: 'active:bg-pink-200', focus: 'focus:ring-2 focus:ring-pink-400 ring-offset-1', border: 'border border-pink-500' },
        light: { background: 'bg-pink-200', foreground: 'text-pink-800', hover: 'hover:bg-pink-100', active: 'active:bg-pink-300', focus: 'focus:ring-2 focus:ring-pink-400 ring-offset-1', border: 'border border-pink-300' },
        dark: { background: 'bg-pink-800', foreground: 'text-white', hover: 'hover:bg-pink-700', active: 'active:bg-pink-900', focus: 'focus:ring-2 focus:ring-pink-500 ring-offset-1', border: 'border border-pink-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-pink-500', hover: 'hover:bg-pink-100', active: 'active:bg-pink-200', focus: 'focus:ring-2 focus:ring-pink-400 ring-offset-1', border: 'border border-transparent' },
    },
    rose: {
        filled: { background: 'bg-rose-500', foreground: 'text-white', hover: 'hover:bg-rose-400', active: 'active:bg-rose-600', focus: 'focus:ring-2 focus:ring-rose-400 ring-offset-1', border: 'border border-rose-500' },
        outline: { background: 'bg-transparent', foreground: 'text-rose-500', hover: 'hover:bg-rose-100', active: 'active:bg-rose-200', focus: 'focus:ring-2 focus:ring-rose-400 ring-offset-1', border: 'border border-rose-500' },
        light: { background: 'bg-rose-200', foreground: 'text-rose-800', hover: 'hover:bg-rose-100', active: 'active:bg-rose-300', focus: 'focus:ring-2 focus:ring-rose-400 ring-offset-1', border: 'border border-rose-300' },
        dark: { background: 'bg-rose-800', foreground: 'text-white', hover: 'hover:bg-rose-700', active: 'active:bg-rose-900', focus: 'focus:ring-2 focus:ring-rose-500 ring-offset-1', border: 'border border-rose-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-rose-500', hover: 'hover:bg-rose-100', active: 'active:bg-rose-200', focus: 'focus:ring-2 focus:ring-rose-400 ring-offset-1', border: 'border border-transparent' },
    },
    slate: {
        filled: { background: 'bg-slate-500', foreground: 'text-white', hover: 'hover:bg-slate-400', active: 'active:bg-slate-600', focus: 'focus:ring-2 focus:ring-slate-400 ring-offset-1', border: 'border border-slate-500' },
        outline: { background: 'bg-transparent', foreground: 'text-slate-500', hover: 'hover:bg-slate-100', active: 'active:bg-slate-200', focus: 'focus:ring-2 focus:ring-slate-400 ring-offset-1', border: 'border border-slate-500' },
        light: { background: 'bg-slate-200', foreground: 'text-slate-800', hover: 'hover:bg-slate-100', active: 'active:bg-slate-300', focus: 'focus:ring-2 focus:ring-slate-400 ring-offset-1', border: 'border border-slate-300' },
        dark: { background: 'bg-slate-800', foreground: 'text-white', hover: 'hover:bg-slate-700', active: 'active:bg-slate-900', focus: 'focus:ring-2 focus:ring-slate-500 ring-offset-1', border: 'border border-slate-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-slate-500', hover: 'hover:bg-slate-100', active: 'active:bg-slate-200', focus: 'focus:ring-2 focus:ring-slate-400 ring-offset-1', border: 'border border-transparent' },
    },
    gray: {
        filled: { background: 'bg-gray-500', foreground: 'text-white', hover: 'hover:bg-gray-400', active: 'active:bg-gray-600', focus: 'focus:ring-2 focus:ring-gray-400 ring-offset-1', border: 'border border-gray-500' },
        outline: { background: 'bg-transparent', foreground: 'text-gray-500', hover: 'hover:bg-gray-100', active: 'active:bg-gray-200', focus: 'focus:ring-2 focus:ring-gray-400 ring-offset-1', border: 'border border-gray-500' },
        light: { background: 'bg-gray-200', foreground: 'text-gray-800', hover: 'hover:bg-gray-100', active: 'active:bg-gray-300', focus: 'focus:ring-2 focus:ring-gray-400 ring-offset-1', border: 'border border-gray-300' },
        dark: { background: 'bg-gray-800', foreground: 'text-white', hover: 'hover:bg-gray-700', active: 'active:bg-gray-900', focus: 'focus:ring-2 focus:ring-gray-500 ring-offset-1', border: 'border border-gray-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-gray-500', hover: 'hover:bg-gray-100', active: 'active:bg-gray-200', focus: 'focus:ring-2 focus:ring-gray-400 ring-offset-1', border: 'border border-transparent' },
    },
    zinc: {
        filled: { background: 'bg-zinc-500', foreground: 'text-white', hover: 'hover:bg-zinc-400', active: 'active:bg-zinc-600', focus: 'focus:ring-2 focus:ring-zinc-400 ring-offset-1', border: 'border border-zinc-500' },
        outline: { background: 'bg-transparent', foreground: 'text-zinc-500', hover: 'hover:bg-zinc-100', active: 'active:bg-zinc-200', focus: 'focus:ring-2 focus:ring-zinc-400 ring-offset-1', border: 'border border-zinc-500' },
        light: { background: 'bg-zinc-200', foreground: 'text-zinc-800', hover: 'hover:bg-zinc-100', active: 'active:bg-zinc-300', focus: 'focus:ring-2 focus:ring-zinc-400 ring-offset-1', border: 'border border-zinc-300' },
        dark: { background: 'bg-zinc-800', foreground: 'text-white', hover: 'hover:bg-zinc-700', active: 'active:bg-zinc-900', focus: 'focus:ring-2 focus:ring-zinc-500 ring-offset-1', border: 'border border-zinc-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-zinc-500', hover: 'hover:bg-zinc-100', active: 'active:bg-zinc-200', focus: 'focus:ring-2 focus:ring-zinc-400 ring-offset-1', border: 'border border-transparent' },
    },
    neutral: {
        filled: { background: 'bg-neutral-500', foreground: 'text-white', hover: 'hover:bg-neutral-400', active: 'active:bg-neutral-600', focus: 'focus:ring-2 focus:ring-neutral-400 ring-offset-1', border: 'border border-neutral-500' },
        outline: { background: 'bg-transparent', foreground: 'text-neutral-500', hover: 'hover:bg-neutral-100', active: 'active:bg-neutral-200', focus: 'focus:ring-2 focus:ring-neutral-400 ring-offset-1', border: 'border border-neutral-500' },
        light: { background: 'bg-neutral-200', foreground: 'text-neutral-800', hover: 'hover:bg-neutral-100', active: 'active:bg-neutral-300', focus: 'focus:ring-2 focus:ring-neutral-400 ring-offset-1', border: 'border border-neutral-300' },
        dark: { background: 'bg-neutral-800', foreground: 'text-white', hover: 'hover:bg-neutral-700', active: 'active:bg-neutral-900', focus: 'focus:ring-2 focus:ring-neutral-500 ring-offset-1', border: 'border border-neutral-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-neutral-500', hover: 'hover:bg-neutral-100', active: 'active:bg-neutral-200', focus: 'focus:ring-2 focus:ring-neutral-400 ring-offset-1', border: 'border border-transparent' },
    },
    stone: {
        filled: { background: 'bg-stone-500', foreground: 'text-white', hover: 'hover:bg-stone-400', active: 'active:bg-stone-600', focus: 'focus:ring-2 focus:ring-stone-400 ring-offset-1', border: 'border border-stone-500' },
        outline: { background: 'bg-transparent', foreground: 'text-stone-500', hover: 'hover:bg-stone-100', active: 'active:bg-stone-200', focus: 'focus:ring-2 focus:ring-stone-400 ring-offset-1', border: 'border border-stone-500' },
        light: { background: 'bg-stone-200', foreground: 'text-stone-800', hover: 'hover:bg-stone-100', active: 'active:bg-stone-300', focus: 'focus:ring-2 focus:ring-stone-400 ring-offset-1', border: 'border border-stone-300' },
        dark: { background: 'bg-stone-800', foreground: 'text-white', hover: 'hover:bg-stone-700', active: 'active:bg-stone-900', focus: 'focus:ring-2 focus:ring-stone-500 ring-offset-1', border: 'border border-stone-800' },
        ghost: { background: 'bg-transparent', foreground: 'text-stone-500', hover: 'hover:bg-stone-100', active: 'active:bg-stone-200', focus: 'focus:ring-2 focus:ring-stone-400 ring-offset-1', border: 'border border-transparent' },
    }, 
}
  